- name: Install the latest version of HAPROXY 
  apt: name=haproxy state=latest 
  tags: haproxy

- name: Push HAPROXY configuration file 
  template: src=haproxy.cfg.j2  dest=/etc/haproxy/haproxy.cfg force=yes owner=root mode=664
  tags: config_push

- name: Enable the HAPROXY
  lineinfile: dest=/etc/default/haproxy
              regexp='^ENABLED='
              line='ENABLED=1'

- name: install mysql-client
  apt: name=mysql-client state=present

- name: Reload haproxy
  service: name=haproxy state=restarted enabled=yes
